services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  app:
    build:
      context: ../../
      dockerfile: apps/backend/.docker/Dockerfile
    ports:
      - "3000:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_BASE_URL=${API_BASE_URL}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - .:/build_
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo_data: