x-service-template: &service-template
  restart: no
  environment:
    - NODE_ENV=${NODE_ENV}
    - API_BASE_URL=${API_BASE_URL}
    - PORT=${PORT}
    - MONGO_URI=${MONGO_URI}
    - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
  volumes:
    - ./packages:/_build/packages
    - ./app/nodemon.json:/_build/app/nodemon.json

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - private

  health:
    <<: *service-template
    container_name: health-${NODE_ENV}
    image: health-${NODE_ENV}
    depends_on:
      - mongo
    build:
      context: ../
      dockerfile: ./app/.docker/Dockerfile
      args:
        SERVICE_NAME: health
    volumes:
      - ./micro-services/health:/app
    ports:
      - 3000:${PORT}
    networks:
      - private

  user:
    <<: *service-template
    container_name: user-${NODE_ENV}
    image: user-${NODE_ENV}
    depends_on:
      - mongo
    build:
      context: ../
      dockerfile: ./app/.docker/Dockerfile
      args:
        SERVICE_NAME: user
    volumes:
      - ./micro-services/user:/app
    ports:
      - 3001:${PORT}
    networks:
      - private

volumes:
  mongo_data:

networks:
  private:
    driver: bridge