name: Check Build Status

on:
  push:
    branches:
      - main

jobs:
  check-build-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build